/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bookingruang;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Viranda
 */
public class adminvalidasi extends javax.swing.JFrame {
    public Connection conn = null;
    public Statement st = null;
    public ResultSet rst = null;
    public DefaultTableModel model;
    public DefaultTableModel model1;
    public PreparedStatement pst;

    /**
     * Creates new form adminvalidasi
     */
    public adminvalidasi() {
        initComponents();
        String[] header = {"Kode Peminjaman","Kode Ruang","Hari","Tanggal","Waktu Mulai","Waktu Selesai","Keterangan","NIM","Status"};
        model = new DefaultTableModel(header,0);
        tabelpakai.setModel(model);
        ruangpakai();
        
        String[] header1 = {"Ruang","Jenis Ruangan","Kapasitas"};
        model1 = new DefaultTableModel(header1,0);
        tabelkosong.setModel(model1);
        daftarkosong();
    }
    
    public void ruangpakai(){
        try{
            model.getDataVector().removeAllElements();
            model.fireTableDataChanged();
            String query = "SELECT kd_pinjam,kd_ruang,hari,tanggal,waktu_mulai,waktu_selesai,keterangan,nim,status FROM pinjam";
            conn = DriverManager.getConnection("jdbc:mysql://localhost/bookingruang","root","");
            pst = conn.prepareStatement(query);
            
            rst = pst.executeQuery();
            
            while (rst.next()){
                String[] row = {rst.getString(1),rst.getString(2),rst.getString(3),
                                rst.getString(4),rst.getString(5),rst.getString(6),
                                rst.getString(7),rst.getString(8),rst.getString(9)};
                model.addRow(row); 
            
            }
            
            
            tabelpakai.setModel(model);    
        }catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void daftarkosong(){
        try{
            String query = "SELECT * FROM ruang where kd_ruang not in (SELECT kd_ruang from pinjam)";
            conn = DriverManager.getConnection("jdbc:mysql://localhost/bookingruang","root","");
            pst = conn.prepareStatement(query);
            
            rst = pst.executeQuery();
            int i = 1;
            while (rst.next()){
                String[] row = {rst.getString(1),rst.getString(2),rst.getString(3)};
                model1.addRow(row); 
                i++;
            }
            tabelkosong.setModel(model1);    
        }catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void klik (adminvalidasi av){
        int pilih = av.tabelpakai.getSelectedRow();
        av.validasi.setSelectedItem(av.tabelpakai.getValueAt(pilih, 9).toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelpakai = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelkosong = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        validasi = new javax.swing.JComboBox<>();
        update = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        logout = new javax.swing.JMenu();
        perkuliahan = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(812, 529));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelpakai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelpakai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelpakaiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelpakai);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 790, 90));

        tabelkosong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabelkosong);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 350, 90));

        jLabel1.setText("Ruang Kosong");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jLabel2.setText("Ruang Terpakai");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        validasi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Belum Divalidasi", "Sudah Divalidasi" }));
        validasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validasiActionPerformed(evt);
            }
        });
        getContentPane().add(validasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 130, -1));

        update.setText("Update");
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateMouseClicked(evt);
            }
        });
        getContentPane().add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, -1));

        logout.setText("Log out");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jMenuBar2.add(logout);

        perkuliahan.setText("Jadwal Perkuliahan GKU");
        perkuliahan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                perkuliahanMouseClicked(evt);
            }
        });
        perkuliahan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perkuliahanActionPerformed(evt);
            }
        });
        jMenuBar2.add(perkuliahan);

        setJMenuBar(jMenuBar2);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:
        login log = new login();
        int pesan=JOptionPane.showConfirmDialog(null, "Yakin ?","Konfirmasi",JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);
        if (pesan==JOptionPane.YES_OPTION){
            log.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_logoutMouseClicked

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_logoutActionPerformed

    private void validasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_validasiActionPerformed

    private void tabelpakaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelpakaiMouseClicked
        // TODO add your handling code here:\
        klik(this);
    }//GEN-LAST:event_tabelpakaiMouseClicked

    private void updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseClicked
        // TODO add your handling code here:
        try{
            String query = "UPDATE pinjam set kd_ruang=?,"+"hari=?,"+"tanggal=?,"+"waktu_mulai=?,"
                            +"waktu_selesai=?,"+"keterangan=?,"+"nim=?,"+"status=?"+"where kd_pinjam=?" ;
            conn = DriverManager.getConnection("jdbc:mysql://localhost/bookingruang","root","");
            pst = conn.prepareStatement(query);
            
            int pilih = tabelpakai.getSelectedRow();
            pst.setString(1, tabelpakai.getValueAt(pilih, 1).toString());
            pst.setString(2, tabelpakai.getValueAt(pilih, 2).toString());
            pst.setString(3, tabelpakai.getValueAt(pilih, 3).toString());
            pst.setString(4, tabelpakai.getValueAt(pilih, 4).toString());
            pst.setString(5, tabelpakai.getValueAt(pilih, 5).toString());
            pst.setString(6, tabelpakai.getValueAt(pilih, 6).toString());
            pst.setString(7, tabelpakai.getValueAt(pilih, 7).toString());
            pst.setString(8, validasi.getSelectedItem().toString());
            pst.setString(9, tabelpakai.getValueAt(pilih, 0).toString());   
            pst.executeUpdate();
            
            ruangpakai();
            
        }catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updateMouseClicked

    private void perkuliahanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_perkuliahanMouseClicked
        // TODO add your handling code here:
        jadwalperkuliahan jp = new jadwalperkuliahan();
        jp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_perkuliahanMouseClicked

    private void perkuliahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perkuliahanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_perkuliahanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminvalidasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminvalidasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminvalidasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminvalidasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminvalidasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenu logout;
    private javax.swing.JMenu perkuliahan;
    private javax.swing.JTable tabelkosong;
    private javax.swing.JTable tabelpakai;
    private javax.swing.JButton update;
    public javax.swing.JComboBox<String> validasi;
    // End of variables declaration//GEN-END:variables
}
